### ISSUE TITLE
Add support for Variant Presets

### ISSUE THREAD

**Issue by kdambekalns** [sitegeist/Sitegeist.Kaleidoscope#12]
I'd have a go at adding support for "variant presets" to Kaleidoscope. But…

First question would be: What to do about the name clash with the existing (thumbnail) `preset` option on `ImageSource`?

Should there be a new option `variant`? And should that be given as `<PresetIdentifier>::<VariantIdentifier>` or rather as two new options `variantPreset` and `variant`?

We could also "reuse" the `preset` option and take it as variant preset when given with `::` in the identifier… too magic?

Any opinions here, @mficzel, @robertlemke, @kitsunet?

**Comment by mficzel** [comment]
@kdambekalns i would go with the name variant as the existing presets are working differntly.

\Sitegeist\Kaleidoscope\EelHelpers\ImageSourceHelperInterface
```
    public function applyVariantPreset(string $group, string $variant) : ImageSourceHelperInterface;
```

While the function has to be implemented in all ImageSourceHelpers it can only have an effect in the scalable ones (Asset and Dummy). 

In the assetImageSource the asset variant will obviously be switched but the target dimensions have to be adjusted for Asset  and Dummy Image sources from the variant configuration.

That way it will be possible to decide the actually used variant on the presentation side which will be especially helpful for picture-tags.

On top of this it obviously makes sense add a variant option to the `Sitegeist.Kaleidoscope:AssetImageSource` and `Sitegeist.Kaleidoscope:AssetImageSource` that internally will calls `applyVariantPreset()`.
