### ISSUE TITLE
Don't render srcset paths that are bigger than the original image

### ISSUE THREAD

**Issue by bweinzierl** [sitegeist/Sitegeist.Kaleidoscope#33]
When the editor uses a small image and the fusion code has bigger sizes defined in the srcset property they are added to the srcset html attribute.
In our project we had strange effects because the browser was expecting an image with a specific width (as defined in srcset) but got an image with a different width than specified. The image in our case was not even upscaled. But even if it were it would make no sense to upscale an image.

This patch fixed the problem for us:

[kaleidoscope-remove-upscaled-srcsets.patch.txt](https://github.com/sitegeist/Sitegeist.Kaleidoscope/files/5942269/kaleidoscope-remove-upscaled-srcsets.patch.txt)

**Comment by bweinzierl** [comment]
We tweaked it a bit to prevent an empty srcset="" if the file is to small to provide even one srcset width.

If this is interesting for anybody i can provide a PR...

**Comment by manuelmeister** [comment]
I like this idea. I'll create a PR with this.

**Comment by manuelmeister** [comment]
@mficzel could there be a case where someone would want to upscale an image beyond the asset image size? Then it would be necessary to add an allowUpscaling flag in the srcset function.

@bweinzierl If we don't render srcset paths for generated images bigger than the original, then we would also need to implement this functionality for the `1x, 2x` specifiers as well.

**Comment by bweinzierl** [comment]
@manuelmeister I tested your PR and it solves our usecase perfectly. 
@mficzel Can we merge this?

**Comment by manuelmeister** [comment]
@bweinzierl  I removed the preserveAspect part to #77. Could you have a look as well there?
